### ISSUE TITLE
Larger / different model types?

### ISSUE THREAD

**Issue by jjhw** [AIRLab-POLIMI/BTGenBot#2]
I was wondering if you were going to do this with larger models, such as 13B and alternative models such as Mistral and Mixtral?

**Comment by Hi-Zed** [comment]
This work was specifically targeted to small models that could run on our hardware. Nonetheless, we are currently doing some tests with llamachat-13B and we will add those adapters to the repo.
We plan to extend this work, but we haven't decided in which direction yet.
