### ISSUE TITLE
igus_rebel_commander

### ISSUE THREAD

**Issue by WEXIJUE** [AIRLab-POLIMI/BTGenBot#5]
Hello author, I am very interested in your work. I encountered an error when reproducing your work, which I cannot solve. I hope you can give me a more detailed explanation of how to reproduce your work!
igus_rebel_commander：可[在此处](https://github.com/AIRLab-POLIMI/ros2-igus-rebel)获得，仅用于bt_client涉及 arucos 和手臂活动的任务。
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/410bde7f-fd4d-42c7-ad77-45a8adac7c87)

**Comment by RiccardoIzzo** [comment]
Hello, unfortunately there is an error with the ros2-igus-rebel repository, in particular with the igus_rebel_servo package. To fix the issue just delete the igus_rebel_servo folder and compile it again.

**Comment by WEXIJUE** [comment]
Thank you very much 

> 您好，很遗憾，ros2-igus-rebel 存储库存在错误，特别是 igus_rebel_servo 包。要修复此问题，只需删除 igus_rebel_servo 文件夹并重新编译即可。

**Comment by WEXIJUE** [comment]
> 您好，很遗憾，ros2-igus-rebel 存储库存在错误，特别是 igus_rebel_servo 包。要修复此问题，只需删除 igus_rebel_servo 文件夹并重新编译即可。

After deleting the ros2-igus-rebel repository, I encountered this error，
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/69bf2f66-36b2-4776-a71c-295dd8380196)

I can find igus_rebel_commander in the src package, but cannot find it in the install, and the error shown in the picture appears. I hope you can reply, thank you very much

**Comment by RiccardoIzzo** [comment]
You have to delete only the package `igus_rebel_servo` which is inside the directory `ros2-igus-rebel`, not the entire directory.

**Comment by WEXIJUE** [comment]
> You have to delete only the package `igus_rebel_servo` which is inside the directory `ros2-igus-rebel`, not the entire directory.

I only deleted igus_rebel_servo   
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/8a07b4f1-fc9d-4d37-bcd2-cbb08db51a85)

**Comment by RiccardoIzzo** [comment]
Have you already built `ros2-igus-rebel` by following the instructions of that repository? I mean with `colcon build --symlink-install` inside the root directory of `ros2-igus-rebel` and in a ros2 workspace.

**Comment by WEXIJUE** [comment]
> Have you already built `ros2-igus-rebel` by following the instructions of that repository? I mean with `colcon build --symlink-install` inside the root directory of `ros2-igus-rebel` and in a ros2 workspace.

ok thank you very much i will check again

**Comment by WEXIJUE** [comment]
> 您是否已经`ros2-igus-rebel`按照该存储库的说明进行构建？我的意思是在 ros2 工作区`colcon build --symlink-install`的根目录中。`ros2-igus-rebel`
I rechecked and rebuilt colcon build --symlink-install in the root directory of ros2-igus-rebel . But the following error still occurred.
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/f2564233-d6a8-4e26-862b-5884897271de)

**Comment by RiccardoIzzo** [comment]
Please have a look at #6, there is a missing dependency.

**Comment by WEXIJUE** [comment]
> 请看一下#6，缺少依赖项。

I would like to use turtlebot3 emulation environment to reproduce your results but I'm running into some issues, could you provide some more detailed clues on using turtlebot3 in emulation environment to execute the client and execute the behavior tree. Thank you so much! ! !

**Comment by RiccardoIzzo** [comment]
Issue transferred to #7
