### ISSUE TITLE
igus_rebel_commander  

### ISSUE THREAD

**Issue by why371323** [AIRLab-POLIMI/BTGenBot#6]
Hello author, I ran colcon build --symlink-install in the root directory of ros2-igus-rebel but I encountered the following error.
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/49426430/3c89cccd-9684-4e02-88c4-693009b588ce)
Hope to get your answer, thank you very much

**Comment by RiccardoIzzo** [comment]
Hi, I think there is a missing dependency in the readme, thank you for pointing out.
You can find the missing package [here](https://github.com/AIRLab-POLIMI/ros2-aruco-pose-estimation/tree/main/aruco_interfaces), you have to build only `aruco_interfaces`, `aruco_pose_estimation` is not necessary.
If you require any further information, let me know.

**Comment by why371323** [comment]
thank you
