### ISSUE TITLE
igus_rebel_commander

### ISSUE THREAD

**Issue by ysuxing** [AIRLab-POLIMI/BTGenBot#8]
Dear Author,

I have been reading your paper and code, and I noticed that only the navigation task has been validated on the TurtleBot3. Could you please provide a more detailed explanation of how other types of tasks, such as robotic arm tasks, can be validated in a simulation environment? For instance, could you specify the choice of robot models and simulation environments? Thank you very much.

Sincerely

**Comment by RiccardoIzzo** [comment]
Hello, we did the complete tests directly on the physical robot, so we don't have a full simulation that exactly replicates that scenario. However, my suggestion is to replicate this test using the Turtlebot3 on Gazebo for what concerns the navigation tasks and, in parallel, work with the manipulator using MoveIt2 as specified in the [`ros2-igus-rebel`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master) package. Here, in [`igus_rebel_commander`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master/igus_rebel_commander), you will find an action server called `manipulator_action_server` that you can start using the launch file `manipulator_action_server.launch.py`. This server handles the `MoveManipulator` action. Additionally, in [`igus_rebel_moveit_config`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master/igus_rebel_moveit_config) you can find more details on how to simulate the robotic arm in a Gazebo environment.

**Comment by ysuxing** [comment]
> 您好，我们直接在物理机器人上进行了完整的测试，因此我们没有完全复制该场景的完整模拟。但是，我的建议是使用 Gazebo 上的 Turtlebot3 复制此测试，以完成与导航任务相关的任务，同时使用包中指定的 MoveIt2 与操纵器一起工作[`ros2-igus-rebel`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master)。在这里[`igus_rebel_commander`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master/igus_rebel_commander)，您将找到一个名为的操作服务器`manipulator_action_server`，您可以使用启动文件启动它`manipulator_action_server.launch.py`。该服务器处理该`MoveManipulator`操作。此外，[`igus_rebel_moveit_config`](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/tree/master/igus_rebel_moveit_config)您可以在中找到有关如何在 Gazebo 环境中模拟机械臂的更多详细信息。

Do you mean that  i can integrate the igus Rebel robotic arm with the TurtleBot3 chassis and verify the feasibility of all tasks in the Gazebo simulation environment?

**Comment by RiccardoIzzo** [comment]
As far as I know not in the same environment, what I meant was to use two separate Gazebo windows, one for the navigation with the Turtlebot3 and the other one for the igus rebel robotic arm for the manipulator tasks.

**Comment by WEXIJUE** [comment]
> As far as I know not in the same environment, what I meant was to use two separate Gazebo windows, one for the navigation with the Turtlebot3 and the other one for the igus rebel robotic arm for the manipulator tasks.

According to your description in igus rebel moveit_config I use the command: $ ros2 launch igus_rebel_moveit_config demo.launch.py ​​load_gazebo:=true hardware_protocol:=ignition load_base:=true
The following error log appeared when simulating the robotic arm.
log：[move_group-4] [WARN] [1719147185.049221068] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1719147185.049251972] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-4] [INFO] [1719147185.089876040] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'stomp'
[move_group-4] [ERROR] [1719147185.102091769] [moveit.ros_planning.planning_pipeline]: Exception while loading planner 'stomp_moveit/StompPlanner': According to the loaded plugin descriptions the class stomp_moveit/StompPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandP
![截图 2024-06-23 20-59-20](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/c63444ca-8fca-48b7-ba1a-5f429763a769)
lannerAvailable plugins: ompl_interface
![截图 2024-06-23 20-56-12](https://github.com/AIRLab-POLIMI/BTGenBot/assets/61787327/07da39f5-3851-48b4-8130-44749718cada)
/OMPLPlanner, pilz_industrial_motion_planner/CommandPlanner
file:///home/fkx/%E5%9B%BE%E7%89%87/%E6%88%AA%E5%9B%BE/%E6%88%AA%E5%9B%BE%202024-06-23%2020-55-47.png
There is nothing in gazebo simulation environment。

**Comment by RiccardoIzzo** [comment]
I'm sorry to hear that but I'm unaware of this error since I never encountered it. However, it seems related to MoveIt2, hence I would suggest you to verify the installation process. In my case, I'm able to load the manipulator arm together with the mobile base only with the command `ros2 launch igus_rebel_moveit_config demo.launch.py load_base:=true load_gazebo:=true hardware_protocol:=ignition` also used by you. In this way, both Rviz and Gazebo launch correctly.
![Screenshot from 2024-06-23 15-36-31](https://github.com/AIRLab-POLIMI/BTGenBot/assets/73133239/16a042c7-1f16-4e4e-a391-ff34801cf895)
![2024-06-23T15:37:32 922038582](https://github.com/AIRLab-POLIMI/BTGenBot/assets/73133239/f8f79d35-cbaa-48ec-9e51-78fcb80fe8d8)
![Screenshot from 2024-06-23 15-50-37](https://github.com/AIRLab-POLIMI/BTGenBot/assets/73133239/be40cce8-a75d-4207-ac10-e29beb3dcb55)
Please check again the installation process with all the related dependencies.

**Comment by WEXIJUE** [comment]
> 很遗憾听到这个消息，但我不知道这个错误，因为我从未遇到过。但是，它似乎与 MoveIt2 有关，因此我建议您验证安装过程。就我而言，我能够仅使用您使用的命令将机械臂与移动基座一起加载`ros2 launch igus_rebel_moveit_config demo.launch.py load_base:=true load_gazebo:=true hardware_protocol:=ignition`。这样，Rviz 和 Gazebo 都可以正确启动。 请再次检查安装过程以及所有相关依赖项。 ![2024-06-23 15-36-31 的截图](https://private-user-images.githubusercontent.com/73133239/342068985-16a042c7-1f16-4e4e-a391-ff34801cf895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDk2NDIsIm5iZiI6MTcxOTIwOTM0MiwicGF0aCI6Ii83MzEzMzIzOS8zNDIwNjg5ODUtMTZhMDQyYzctMWYxNi00ZTRlLWEzOTEtZmYzNDgwMWNmODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZTA3M2RiNGUwZjhhYjY4Zjk3Y2VhNmU5ZTVhZTU2MjgxZTFjY2Q5YmNjNGJjMzRlZmViOTE5MDRiYjg5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6e2VaQbkFEOUZwM4SV-Asg57cXBO8TOBdKoEATdiD9o) ![2024-06-23T15:37:32 922038582](https://private-user-images.githubusercontent.com/73133239/342069069-f8f79d35-cbaa-48ec-9e51-78fcb80fe8d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDk2NDIsIm5iZiI6MTcxOTIwOTM0MiwicGF0aCI6Ii83MzEzMzIzOS8zNDIwNjkwNjktZjhmNzlkMzUtY2JhYS00OGVjLTllNTEtNzhmY2I4MGZlOGQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzUwYTdlYjFmZTI1M2ViZDBiY2U1NTQzMDM3MWNmZTI3OGE1ZjUyZGYzYjVhMmYyMjRhY2MxYzdlMDQzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xUMn_FQmSLYYbe773YydmfBEN1CguxcjpeJl1_ONW6E) ![2024-06-23 15-50-37 的截图](https://private-user-images.githubusercontent.com/73133239/342069388-be40cce8-a75d-4207-ac10-e29beb3dcb55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDk2NDIsIm5iZiI6MTcxOTIwOTM0MiwicGF0aCI6Ii83MzEzMzIzOS8zNDIwNjkzODgtYmU0MGNjZTgtYTc1ZC00MjA3LWFjMTAtZTI5YmViM2RjYjU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2UyZGFkMTI3NThmYjQ3NzBjMDFhNDUxOTEwNGYwODk0MWViZWQ5N2MxN2FlM2RmNWEwNjUwZTE4ZjFmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sxuS6qA63_uOuavehjHxffF3XsTG8bmqkJ6EB30M-C4)


Thank you very much for your reply. Does installing moveit2 have to be built from source? Is the workspace of moveit consistent with that of igus-rebel?

**Comment by RiccardoIzzo** [comment]
Yes, install it from [source](https://moveit.ros.org/install-moveit2/source/) and check out the demos in the quickstart. It is sufficient to have both MoveIt2 and igus-rebel in your ROS2 workspace.
